instance_destroy(mymove)
instance_destroy(myclose)
instance_destroy(myminimize)
instance_destroy(obj_taskbar_select)
ds_list_delete(obj_menu.taskbar_list, ds_list_find_index(obj_menu.taskbar_list, obj_taskbar_select))